<a href="https://colab.research.google.com/github/Sandeep-golidatai/Genarative-AI/blob/main/Bert_embedded_ipyn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers


In [ ]:
from transformers import BertModel,BertTokenizer

In [ ]:
bert_model=BertModel.from_pretrained('bert-base-uncased')
# model name is bert-base-uncased
# bert_token=BertTokenizer

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
bert_model.base_model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

In [ ]:
dir(bert_model)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_assisted_decoding',
 '_auto_class',
 '_autoset_attn_implementation',
 '_backward_compatibility_gradient_checkpointing',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_beam_sample',
 '_beam_search',
 '_buffers',
 '_call_impl',
 '_check_and_enable_flash_attn_2',
 '_check_and_enable_sdpa',
 '_compiled_call_impl',
 '_constrained_beam_search',
 '_contrastive_search',
 '_convert_head_mask_to_5d',
 '_copy_lm_head_original_to_resized',
 '_create_repo',
 '_dispatch_accelerate_model',
 '_expand_inputs_for_generation',
 

Bert Tokenizer

In [ ]:
sentence='we are learning bert embedding'

In [ ]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")
tokenizer

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

BertTokenizer(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

sep_token is used to seperate the sentence
cls_token is used to close the senctence
max length is 512
number of words given is 7
but required is 512 so,padding is do



In [ ]:
dir(tokenizer)

['SPECIAL_TOKENS_ATTRIBUTES',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_tokens',
 '_added_tokens_decoder',
 '_added_tokens_encoder',
 '_additional_special_tokens',
 '_auto_class',
 '_batch_encode_plus',
 '_batch_prepare_for_model',
 '_bos_token',
 '_call_one',
 '_cls_token',
 '_compile_jinja_template',
 '_convert_id_to_token',
 '_convert_token_to_id',
 '_convert_token_to_id_with_added_voc',
 '_create_repo',
 '_decode',
 '_decode_use_source_tokenizer',
 '_encode_plus',
 '_eos_token',
 '_eventual_warn_about_too_long_sequence',
 '_eventually_correct_t5_max_length',
 '_from_pretrained',
 '_get_files_timestamps',
 '_g

In [ ]:
tokenizer.vocab

OrderedDict([('[PAD]', 0),
             ('[unused0]', 1),
             ('[unused1]', 2),
             ('[unused2]', 3),
             ('[unused3]', 4),
             ('[unused4]', 5),
             ('[unused5]', 6),
             ('[unused6]', 7),
             ('[unused7]', 8),
             ('[unused8]', 9),
             ('[unused9]', 10),
             ('[unused10]', 11),
             ('[unused11]', 12),
             ('[unused12]', 13),
             ('[unused13]', 14),
             ('[unused14]', 15),
             ('[unused15]', 16),
             ('[unused16]', 17),
             ('[unused17]', 18),
             ('[unused18]', 19),
             ('[unused19]', 20),
             ('[unused20]', 21),
             ('[unused21]', 22),
             ('[unused22]', 23),
             ('[unused23]', 24),
             ('[unused24]', 25),
             ('[unused25]', 26),
             ('[unused26]', 27),
             ('[unused27]', 28),
             ('[unused28]', 29),
             ('[unused29]', 30),
  

In [ ]:
len(tokenizer.vocab)

30522

In [ ]:
tokenizer.vocab_size

30522

In [ ]:
tokenizer.vocab.keys()

odict_keys(['[PAD]', '[unused0]', '[unused1]', '[unused2]', '[unused3]', '[unused4]', '[unused5]', '[unused6]', '[unused7]', '[unused8]', '[unused9]', '[unused10]', '[unused11]', '[unused12]', '[unused13]', '[unused14]', '[unused15]', '[unused16]', '[unused17]', '[unused18]', '[unused19]', '[unused20]', '[unused21]', '[unused22]', '[unused23]', '[unused24]', '[unused25]', '[unused26]', '[unused27]', '[unused28]', '[unused29]', '[unused30]', '[unused31]', '[unused32]', '[unused33]', '[unused34]', '[unused35]', '[unused36]', '[unused37]', '[unused38]', '[unused39]', '[unused40]', '[unused41]', '[unused42]', '[unused43]', '[unused44]', '[unused45]', '[unused46]', '[unused47]', '[unused48]', '[unused49]', '[unused50]', '[unused51]', '[unused52]', '[unused53]', '[unused54]', '[unused55]', '[unused56]', '[unused57]', '[unused58]', '[unused59]', '[unused60]', '[unused61]', '[unused62]', '[unused63]', '[unused64]', '[unused65]', '[unused66]', '[unused67]', '[unused68]', '[unused69]', '[unused7

In [ ]:
tokenizer.vocab["hello"]

7592

In [ ]:
tokenizer.vocab["machine"]

3698

In [ ]:
tokens=tokenizer.tokenize("machinelearning")
tokens

['machine', '##lea', '##rn', '##ing']

In [ ]:
tokens=tokenizer.tokenize("machine learning")
tokens

['machine', 'learning']

In [ ]:
sentence='we are learning bert embedding'
tokens=tokenizer.tokenize(sentence)
tokens

['we', 'are', 'learning', 'bert', 'em', '##bed', '##ding']

In [ ]:
tokenizer.vocab['##bed'],tokenizer.vocab['bed']

(8270, 2793)

In [ ]:
token1=['[CLS]']+tokens+['[SEP]']
token1

['[CLS]', 'we', 'are', 'learning', 'bert', 'em', '##bed', '##ding', '[SEP]']

In [ ]:
token2=['[CLS]'] + tokens + ['[SEP]']+ ['[CLS]'] + tokens + ['[PAD]']
token2

['[CLS]',
 'we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '[SEP]',
 '[CLS]',
 'we',
 'are',
 'learning',
 'bert',
 'em',
 '##bed',
 '##ding',
 '[PAD]']

**Attention Mask**

In [ ]:
attention_mask=[1     if i!='[PAD]'     else 0           for i in token2]
attention_mask

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]

**Convet tokens to ids**

In [ ]:
token_ids=tokenizer.convert_tokens_to_ids(token2)
token_ids

[101,
 2057,
 2024,
 4083,
 14324,
 7861,
 8270,
 4667,
 102,
 101,
 2057,
 2024,
 4083,
 14324,
 7861,
 8270,
 4667,
 0]

In [ ]:
import torch
ids=torch.tensor(token_ids).unsqueeze(0)
mask=torch.tensor(attention_mask).unsqueeze(0)


In [ ]:
ids

tensor([[  101,  2057,  2024,  4083, 14324,  7861,  8270,  4667,   102,   101,
          2057,  2024,  4083, 14324,  7861,  8270,  4667,     0]])

In [ ]:
mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])

In [ ]:
out=bert_model(ids,mask)
out

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.0681,  0.1164, -0.1680,  ..., -0.4496, -0.1853,  0.5617],
         [ 0.3236, -0.0720, -0.4538,  ...,  0.1225,  0.9802, -0.4723],
         [-0.0345,  0.2552, -0.1493,  ..., -0.1867, -0.0135,  0.3236],
         ...,
         [ 0.4997, -0.0708, -0.0153,  ...,  0.0560, -0.5962, -0.1663],
         [-0.2493, -0.1621, -0.5617,  ...,  0.0693, -0.6352,  0.6794],
         [ 0.2460, -0.1517,  0.3514,  ..., -0.1605, -0.3517, -0.0582]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.9519, -0.5242, -0.9138,  0.8459,  0.7023, -0.3120,  0.9363,  0.2764,
         -0.7769, -1.0000, -0.5545,  0.9418,  0.9921,  0.3930,  0.9468, -0.7492,
         -0.4471, -0.5392,  0.4823, -0.6573,  0.8007,  1.0000,  0.2829,  0.3685,
          0.4847,  0.9935, -0.8679,  0.9523,  0.9699,  0.7762, -0.7824,  0.2607,
         -0.9939, -0.2739, -0.9447, -0.9961,  0.5424, -0.8349,  0.0171, -0.0144,
         -0.9540,  0.4081,  1.00

In [ ]:
out[0].shape

# we have 20 tokesn are there
# this give eeach token embbedded vecotr
# vercot has 768 weights
# 1 sentance
# 20 tokens
# 768 values vectors
# 1, 20, 768

torch.Size([1, 18, 768])

In [ ]:
# out.items()
out.last_hidden_state
#out[0].shape


tensor([[[-0.0681,  0.1164, -0.1680,  ..., -0.4496, -0.1853,  0.5617],
         [ 0.3236, -0.0720, -0.4538,  ...,  0.1225,  0.9802, -0.4723],
         [-0.0345,  0.2552, -0.1493,  ..., -0.1867, -0.0135,  0.3236],
         ...,
         [ 0.4997, -0.0708, -0.0153,  ...,  0.0560, -0.5962, -0.1663],
         [-0.2493, -0.1621, -0.5617,  ...,  0.0693, -0.6352,  0.6794],
         [ 0.2460, -0.1517,  0.3514,  ..., -0.1605, -0.3517, -0.0582]]],
       grad_fn=<NativeLayerNormBackward0>)

In [ ]:
pip install langchain


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 973.7/973.7 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.9/307.9 kB 16.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.2/121.2 kB 13.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.5/142.5 kB 8.8 MB/s eta 0:00:00
  Attempting uninstall: packaging
    Found existing installation: packaging 24.0
    Uninstalling packaging-24.0:
      Successfully uninstalled packaging-24.0


In [ ]:
import langchain

In [ ]:
dir(langchain)

['Any',
 'Optional',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_warn_on_import',
 'surface_langchain_deprecation_warnings',
 'warnings']